### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by wangshunping** [noirbizarre/flask-restplus#113]
When I download this package and run examples
```
python examples/todo_blueprint.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 494-363-078
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /api/1/ HTTP/1.1" 200 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/css/typography.css HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/css/reset.css HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/css/screen.css HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery-1.8.0.min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.slideto.min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.wiggle.min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.ba-bbq.min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/lib/handlebars-2.0.0.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/lib/backbone-min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/lib/highlight.7.3.pack.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/lib/marked.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/lib/underscore-min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/swagger-ui.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 18:09:30] "GET /swaggerui/bower/swagger-ui/dist/lib/swagger-oauth.js HTTP/1.1" 404 -
```

How can i connect with swagger?

**Comment by noirbizarre** [comment]
Hi !

This is because you need to download the assets with bower first:
```console
$ bower install
```
It's not necessary if you installed it from PyPI, but it's needed to develop (et run the example).

**Comment by wangshunping** [comment]
My system is Mac 10.10.

I have install bower using npm
```
(orivenv)guo@pingdeMacBook-Air-2 flask-restplus$ sudo npm install -g bower
Password:
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
bower@1.7.1 /usr/local/lib/node_modules/bower
└── semver-utils@1.1.1
```
But when I using 
```
guo@pingdeMacBook-Air-2 flask-restful-swagger$ bower install
/usr/local/lib/node_modules/bower/node_modules/configstore/index.js:56
				throw err;
				^

Error: EACCES: permission denied, open '/Users/guo/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:549:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:397:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
guo@pingdeMacBook-Air-2 flask-restful-swagger$ sudo bower install
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
```

Crying.....

**Comment by noirbizarre** [comment]
Since bower is installed. I the only thing necessary is to run bower without sudo. Assets will be installed in the project folder.
But, I think, you are not in the right project folder because your stacktrace says you are in `flask-restful-swagger` ;)

**Comment by wangshunping** [comment]
Sorry.. :)

I find flask-restful-swagger not pythonic enough, so i am here...

```
(orivenv)guo@pingdeMacBook-Air-2 flask-restplus$ sudo bower install --allow-root


  2 {
bower swagger-ui#~2.1.3     not-cached git://github.com/wordnik/swagger-ui.git#~2.1.3
bower swagger-ui#~2.1.3        resolve git://github.com/wordnik/swagger-ui.git#~2.1.3
bower swagger-ui#~2.1.3       download https://github.com/wordnik/swagger-ui/archive/v2.1.3.tar.gz
bower swagger-ui#~2.1.3       checkout v2.1.3
bower swagger-ui#~2.1.3       progress remote: Compressing objects:   0% (1/119)
bower swagger-ui#~2.1.3       progress remote: Compressing objects:   1% (2/119)
bower swagger-ui#~2.1.3       progress remote: Compressing objects:   2% (3/119)
bower swagger-ui#~2.1.3       progress remote: Compressing objects:   3% (4/119)
bower swagger-ui#~2.1.3       progress remote: Compressing objects:   4% (5/119)
bower swagger-ui#~2.1.3       progress Receiving objects:  41% (54/130), 188.00 KiB | 265.00 KiB/s
bower swagger-ui#~2.1.3       progress Receiving objects:  42% (55/130), 188.00 KiB | 265.00 KiB/s
bower swagger-ui#~2.1.3       progress Receiving objects:  59% (77/130), 340.00 KiB | 269.00 KiB/s
bower swagger-ui#~2.1.3       progress Receiving objects:  59% (77/130), 684.00 KiB | 286.00 KiB/s
bower swagger-ui#~2.1.3       progress Receiving objects:  60% (78/130), 872.00 KiB | 254.00 KiB/s
bower swagger-ui#~2.1.3       progress Receiving objects:  60% (78/130), 948.00 KiB | 216.00 KiB/s
bower swagger-ui#~2.1.3       resolved git://github.com/wordnik/swagger-ui.git#2.1.3
bower swagger-ui#~2.1.3        install swagger-ui#2.1.3

swagger-ui#2.1.3 flask_restplus/static/bower/swagger-ui
```

I have install using sudo bower install --allow-root

```
(orivenv)guo@pingdeMacBook-Air-2 flask-restplus$ python examples/todo_blueprint.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 494-363-078
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /api/1/ HTTP/1.1" 200 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/css/typography.css HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/css/reset.css HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/css/screen.css HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery-1.8.0.min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.slideto.min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.wiggle.min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.ba-bbq.min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/lib/handlebars-2.0.0.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/lib/underscore-min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/lib/backbone-min.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/swagger-ui.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/lib/highlight.7.3.pack.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/lib/marked.js HTTP/1.1" 404 -
127.0.0.1 - - [28/Dec/2015 19:57:11] "GET /swaggerui/bower/swagger-ui/dist/lib/swagger-oauth.js HTTP/1.1" 404 -

```


... What can i do..

**Comment by wangshunping** [comment]
```
(orivenv)guo@pingdeMacBook-Air-2 dist$ l
total 5456
drwxr-xr-x   7 root  wheel   238B 12 28 19:50 css
drwxr-xr-x  12 root  wheel   408B 12 28 19:50 fonts
drwxr-xr-x  10 root  wheel   340B 12 28 19:50 images
-rw-r--r--   1 root  wheel   4.4K 12 28 19:50 index.html
drwxr-xr-x   9 root  wheel   306B 12 28 19:50 lang
drwxr-xr-x  13 root  wheel   442B 12 28 19:50 lib
-rw-r--r--   1 root  wheel   449B 12 28 19:50 o2c.html
-rw-r--r--   1 root  wheel   2.3M 12 28 19:50 swagger-ui.js
-rw-r--r--   1 root  wheel   361K 12 28 19:50 swagger-ui.min.js
(orivenv)guo@pingdeMacBook-Air-2 dist$ pwd
/Users/guo/Code/repository/03.original_code/00.python_origin_code/flask-restplus/flask_restplus/static/bower/swagger-ui/dist
```


As you can see, I really success installed.

**Comment by wangshunping** [comment]
Oh i get it !!!

I install it again~~

```
$ python setup.py develop
```

Now it success~

**Comment by noirbizarre** [comment]
;)

I will improve documentation for both users and developers in the coming weeks.

**Comment by harishkashyap** [comment]
@noirbizarre great job, but the docs need to improve.

**Comment by noirbizarre** [comment]
@harishkashyap Thanks ! I know doucmentation is lacking but a new documentation is coming ;)
