### ISSUE TITLE
abort with 500 not working correctly

### ISSUE THREAD

**Issue by mavoi** [noirbizarre/flask-restplus#143]
I have implemented a simple Flask API call as you can see below:
```
@api.route('/test')
class TestApi(Resource):
    def get(self):
        abort(500, "Test")
```
When I call the url in my browser the console shows the following ouput:
```
ERROR:test:Exception on /test [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/flask_restplus/api.py", line 310, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/pi/Desktop/testServer/test/api/beta/tests/resources.py", line 169, in get
    abort(500, "Test")
  File "/usr/local/lib/python3.4/dist-packages/flask_restplus/errors.py", line 29, in abort
    flask.abort(code)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/exceptions.py", line 646, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500: Internal Server Error
INFO:werkzeug:192.168.52.186 - - [02/Mar/2016 21:01:11] "GET /test HTTP/1.1" 500 -
```
To me this looks like there is an Internal Server Error raised while I abort with 500. The 500 is delivered to the browser as you can see in the last line. Key line should be this:
```
raise self.mapping[code](*args, **kwargs)
```
But why is this happening? I've already registered an errohandler for 500 code but that doesn't work either.

Cheerz

**Comment by noirbizarre** [comment]
Hi !

Sorry for the late response. I'll need a little bit more input to understand you issue because HTTP error 500 is officially "Internal Server Error" so there is nothing wrong to me here.

What did you have as response ? What did you expect instead ? Can you show me the errorhandler you declared ?
