### ISSUE TITLE
Using abort with custom messages prints a massive traceback in console

### ISSUE THREAD

**Issue by RPiAwesomeness** [noirbizarre/flask-restplus#212]
I'm using the `abort()` functionality in RESTPlus to return an error and it returns everything properly. However, I get this mess in my console:

```python
--------------------------------------------------------------------------------
ERROR in app [/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask/app.py:1587]:
Exception on /command/1 [GET]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/api.py", line 309, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/marshalling.py", line 101, in wrapper
    resp = f(*args, **kwargs)
  File "/home/nate/CactusAPI/app/resources/command.py", line 58, in get
    abort(500, "foo", custom="bar", spam="eggs")
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/errors.py", line 29, in abort
    flask.abort(code)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/werkzeug/exceptions.py", line 646, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500: Internal Server Error
2016-10-25 13:12:17 nate-Thinkpad-W520 app[14146] ERROR Exception on /command/1 [GET]
Traceback (most recent call last):
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/api.py", line 309, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/marshalling.py", line 101, in wrapper
    resp = f(*args, **kwargs)
  File "/home/nate/CactusAPI/app/resources/command.py", line 58, in get
    abort(500, "foo", custom="bar", spam="eggs")
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/errors.py", line 29, in abort
    flask.abort(code)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/werkzeug/exceptions.py", line 646, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500: Internal Server Error
```

I understand that this may be caused by `werkzeug`, but I was wondering if there is any way I can return an error without having to have that massive traceback spamming my server log/console?

**Comment by RPiAwesomeness** [comment]
I missed the part in the RTD about explicitly utilizing `marshal`. So, this is less of a bug.

However, it would be nice to have the `abort()` call not spam 40+ lines of traceback information.

**Comment by aqisnotliquid** [comment]
You can use the following in one of the Resource methods:

`return { 'error': 'This is a generic error message.' }, 403`

Flask-RestPlus will jsonify the output and you can parse it however you want on the other side.

**Comment by noirbizarre** [comment]
I don't think this is directly related to Flask-restplus as underneath it uses the flask original `abort` but I'll see what I can do

**Comment by RPiAwesomeness** [comment]
Awesome, thanks! If I ever have some downtime I'll definitely take a look too, maybe come up with a pullreq.
