### ISSUE TITLE
TypeError: unorderable types: str() < int() with many=True nested schema

### ISSUE THREAD

**Issue by RPiAwesomeness** [noirbizarre/flask-restplus#220]
I have a schema that's expecting a list/array of a nested schema:
`arguments = fields.Nested(MessagePacketSchema, many=True)`

And this is `MessagePacketSchema`:
```python
class MessagePacketSchema(Schema):
    type = fields.String(required=True)
    data = fields.String(required=True)
    text = fields.String(required=True)
```

Validation works fine under certain circumstances, such as when the key is passed with a single item of any sort (string, list, dict, etc.) or when it's a list with an incorrect dict within the list. However, if I try to pass a list of strings, integers, floats, etc. (any non-dict type) it throws this massive traceback.

**Passed data**:
`{"arguments": ["this will fail"]}` or `{"arguments": [1, 4, 42]}` for example

**Traceback**:
```Traceback (most recent call last):
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/api.py", line 313, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/api.py", line 334, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/nate/CactusAPI/venv/lib/python3.5/site-packages/flask_restplus/representations.py", line 23, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 352, in _iterencode_dict
    items = sorted(dct.items(), key=lambda kv: kv[0])
TypeError: unorderable types: str() < int()
```

This would appear to be a Flask-RESTPlus issue, based on the traceback, but it could also be related to [Marshmallow Issue #493](https://github.com/marshmallow-code/marshmallow/issues/493).

**Comment by RPiAwesomeness** [comment]
One thing I discovered, if I turn off Flask's debug mode I get no 500/traceback, but get this in response:

```json
{
  "arguments": {
    "_schema": [
      "Invalid input type."
    ]
  }
}
```

**Comment by RPiAwesomeness** [comment]
Turns out this is caused by Marshmallow's usage of numeric keys in it's dicts, which obviously cannot be sorted by Flask-RESTPlus. This is resolvable by converting all keys to strings before sorting
