### ISSUE TITLE
404 and 500 errors on /swagger.json - unhashable type: 'dict'

### ISSUE THREAD

**Issue by franfabrizio** [noirbizarre/flask-restplus#292]
When trying to start up my flask-restplus app, I'm getting swagger-related errors. Interestingly, the error is different whether I am using stable or dev version of flask-restplus.

With flask-restplus 0.10.1 I get 500 error on /swagger.json - unhashable type: 'dict'.  (See full traceback below)

With flask-restplus 0.10.1dev0 I get 404s on all the swagger stuff:
127.0.0.1 - - [16/Jun/2017 08:19:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Jun/2017 08:19:05] "GET /swaggerui/bower/swagger-ui/dist/css/typography.css HTTP/1.1" 404 -
127.0.0.1 - - [16/Jun/2017 08:19:05] "GET /swaggerui/bower/swagger-ui/dist/css/reset.css HTTP/1.1" 404 -
[snip lots more 404s]

It was working fine for a couple of weeks, so I'm thinking I introduced something bad in my app code, but the traceback doesn't reference any of my own code at all. Any thoughts on what I've done to create this behavior?

Here's the error output with flask-restplus 0.10.1:

ERROR in app [/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask/app.py:1560]:
Exception on /swagger.json [GET]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/api.py", line 771, in get
    return self.api.__schema__
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/werkzeug/utils.py", line 73, in __get__
    value = self.func(obj)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/api.py", line 472, in __schema__
    self._schema = Swagger(self).as_dict()
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/swagger.py", line 168, in as_dict
    paths[extract_path(url)] = self.serialize_resource(ns, resource, url, kwargs)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/swagger.py", line 307, in serialize_resource
    path[method] = self.serialize_operation(doc, method)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/swagger.py", line 313, in serialize_operation
    'responses': self.responses_for(doc, method) or None,
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/swagger.py", line 398, in responses_for
    responses[code]['schema'] = self.serialize_schema(model)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/swagger.py", line 433, in serialize_schema
    self.register_model(model)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/swagger.py", line 462, in register_model
    self.register_field(field)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/swagger.py", line 472, in register_field
    self.register_field(field.container)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/swagger.py", line 470, in register_field
    self.register_model(field.nested)
  File "/Users/fran/anaconda3/envs/bibapi/lib/python3.6/site-packages/flask_restplus/swagger.py", line 453, in register_model
    if name not in self.api.models:
TypeError: unhashable type: 'dict'

**Comment by franfabrizio** [comment]
NEVERMIND. It was a PEBKAC. I foobar'ed my nested api model definitions.

**Comment by moritzschaefer** [comment]
@franfabrizio Could you elaborate on that (even though it's a long time ago). I've got the same issue but I can't find the ffobar in my nested API

**Comment by Ligemer** [comment]
This is greatly needed in the documentation or I completely missed it.

@moritzschaefer are you aware if that example exists in docs?

I didn't read anywhere that the additional `api.model()` was required. Thank you.

This ended up working for me:
`field = fields.List(fields.Nested(api.model('TheModel', {'a': fields.String})));`

**Comment by moritzschaefer** [comment]
As stated here in the most recent comment https://github.com/noirbizarre/flask-restplus/issues/8, the documentation (https://flask-restplus.readthedocs.io/en/latest/marshalling.html#nested-field) still states that it supports dict-based Nested fields. Feel free to update :)

**Comment by codectl** [comment]
Thing is, I am pretty sure this was working as I used to have and out of a sudden it stopped working. I rolled back to an older version of the code and it throws me the error.

I used to have something like mentioned above:

`field = fields.Nested({'a': fields.String})`

It was working that way. And it makes sense to me bcs I want to create anonymous models as oppose to having to name each individual model/dict.

**Comment by EduardKononov** [comment]
@rena2damas you should consider migrating to flask-restx, flask-restplus is officially dead. It does not work there too thought :)

**Comment by codectl** [comment]
@EduardKononov thanks for the tip. I haven't come across restx but I did move away from restplus. The missing support for openapi 3 was also a reason. So I ended up going for flask-restful wired up with flasgger & marshmallow (for the data serialization).
