### ISSUE TITLE
Using JSON Schema models

### ISSUE THREAD

**Issue by siddharthist** [noirbizarre/flask-restplus#293]
I'm trying to use a JSON schema to generate a model to be used with `marshal_with`. Here's my MWE:
```python
#!/usr/bin/env python3
from flask import Flask, Blueprint
from flask_restplus import Resource, Api, fields
import json

app = Flask(__name__)
blueprint = Blueprint("api", __name__)
api = Api(blueprint, version="0.1", title="title")
app.register_blueprint(blueprint)

model = api.schema_model("Response", {"type": "string"})

@api.route("/hello")
class Analyze(Resource):
    @api.marshal_with(model)
    def get(self):
        return 5

if __name__ == "__main__":
    app.run(debug=True)
```
When you visit `localhost:5000/hello`, the following traceback occurs:
```
Traceback (most recent call last):
  File "/nix/store/nl9a0l5dvrc3c8y8110qihfcbdzgy5zl-python3.6-flask-0.12/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/nix/store/nl9a0l5dvrc3c8y8110qihfcbdzgy5zl-python3.6-flask-0.12/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nix/store/nhg8sdk9nwqkghk9xwwb69dybjxbj1gz-python3.6-flask-restplus-0.10.1/lib/python3.6/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/nix/store/nl9a0l5dvrc3c8y8110qihfcbdzgy5zl-python3.6-flask-0.12/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/nix/store/nhg8sdk9nwqkghk9xwwb69dybjxbj1gz-python3.6-flask-restplus-0.10.1/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/nix/store/nhg8sdk9nwqkghk9xwwb69dybjxbj1gz-python3.6-flask-restplus-0.10.1/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 110, in wrapper
    return marshal(resp, self.fields, self.envelope, mask)
  File "/nix/store/nhg8sdk9nwqkghk9xwwb69dybjxbj1gz-python3.6-flask-restplus-0.10.1/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 54, in marshal
    for k, v in list(fields.items()))
AttributeError: 'SchemaModel' object has no attribute 'items'
```
I'm just trying to use a `SchemaModel` in the same way I would use a `Model`, like in the following example (which works):
```python
model = api.model("Response", {"field": fields.String(required=True)})

@api.route("/hello")
class Analyze(Resource):
    @api.marshal_with(model)
    def get(self):
        return {"field": "str"}
```
How can I use the JSON schema-generated model?

**Comment by apricat** [comment]
Hi,

I also had issues with schema marshalling so I decided to take a step back and try to get it to work with the supplied basic TodoMVC example.

On the `10.0.1` dist I was able to successfully get marshalling with `schema_model` to work. E.g.

```
todo = api.schema_model('Todo', {
    'properties': {
        'id': {
            'type': 'string'
        },
        'task': {
            'type': 'string'
        }
    },
    'type': 'object'
})
```

```
@ns.route('/')
class TodoList(Resource):
    '''Shows a list of all todos, and lets you POST to add new tasks'''
    @ns.doc('list_todos')
    @ns.marshal_list_with(todo)
    def get(self):
        '''List all tasks'''
        return DAO.todos

    @ns.doc('create_todo')
    @ns.expect(todo)
    @ns.marshal_with(todo, code=201)
    def post(self):
        '''Create a new task'''
        return DAO.create(api.payload), 201
```

I believe your issue stands with the fact that your schema object is malformed. The root object should be 'properties', and you'll want to with a list of fields and their types, just like it is explained in the JSON Schema structure established by the *Draft v4* standard: http://json-schema.org/examples.html

Hoping this helps!

**Comment by siddharthist** [comment]
@apricat Thanks for looking into it! Seems like a full example in the documentation might be useful.

**Comment by lekjart** [comment]
I am getting the exact same error with the following schema:
`category_struct = api.schema_model('BlogCategory', {
    'properties': {
        'id':{
            'type': 'integer'
        },
        'name':{
            'type':'string'
        }
    },
    'required': ['id', 'name'],
    'type': 'object'
})`

**Comment by KpaBap** [comment]
I'm having this issue as well. Seems like flask-restplus really has no way to support nested objects in either JSON schema format or its own models.

My schema that passes online validation:
`{
    'properties': {
        'MainObject':
            {
                'type': 'object',
                'properties': {
                    'NestedObject': {
                        'type': 'string',
                         'required': True
                    }
                }
            }
    },
    'type': 'object'
}`

**Comment by lamehost** [comment]
@apricat what version of python are you running?

On 2.7.14 _items()_ is definitely missing from objects instantiated out of _SchemaModel_
```
Python 2.7.14 (default, Sep 17 2017, 18:50:44) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask_restplus.model import Model, SchemaModel
>>> [_ for _ in dir(Model('foo')) if _ == 'items']
['items']
>>> [_ for _ in dir(SchemaModel('foo')) if _ == 'items']
[]
>>>
```

**Comment by lamehost** [comment]
Hello,

Method [schema_mode()](https://github.com/noirbizarre/flask-restplus/blob/4609dc17e8ea04033984aa0f06c4d583ecf16aca/flask_restplus/namespace.py#L146) makes use of class [SchemaModel](https://github.com/noirbizarre/flask-restplus/blob/4609dc17e8ea04033984aa0f06c4d583ecf16aca/flask_restplus/model.py#L225), while [model()](https://github.com/noirbizarre/flask-restplus/blob/4609dc17e8ea04033984aa0f06c4d583ecf16aca/flask_restplus/namespace.py#L136) makes use of [Model](https://github.com/noirbizarre/flask-restplus/blob/4609dc17e8ea04033984aa0f06c4d583ecf16aca/flask_restplus/model.py#L118).

Class _Model_ inerhits _fields_ from _OrderedDict_ and fills it with the items of the dict passed to _model_().
Method [marshal()](https://github.com/noirbizarre/flask-restplus/blob/4609dc17e8ea04033984aa0f06c4d583ecf16aca/flask_restplus/marshalling.py#L13) walks over _items_ by assuming they're [fields objects](https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/fields.py).

Class _SchemaModel_ does not deal with _fields_ at all.

That to say you can't marshal anything with schema models.

**Comment by Mumrau** [comment]
Hi @lamehost 

I don't really get it since in the very flask restful website it says that we can use schema model for marshalling: http://flask-restplus.readthedocs.io/en/stable/marshalling.html#define-model-using-json-schema

It's all pretty unclear to me here, maybe you can clarify a little bit?

Thanks.

**Comment by lamehost** [comment]
@Mumrau,

I don't have any better explanation.
Maybe it's on TODO, i don't know

**Comment by DHager** [comment]
Ran into this same issue, not sure whether I'm doing something fundamentally-wrong or whether it's a documentation problem.

Currently I'm trying out that idea that maybe one is intended to partially (rather than wholly) replace the other. This experiment is promising, but it's too soon to be sure I'm not just creating an abomination that wasn't intended to live.

```python
todo_model = api.model('Todo', {        
    'task': fields.String(required=True, description='The task details (model)'),
})

todo_schema = api.schema_model('Todo', {
    'properties': {
        'task': {
            'type': 'string',
            'description': 'The task details (schema_model)',
        },
    },
    'type': 'object'
})


@ns.route('/todo/<int:todo_id>')
@ns.response(404, 'Todo not found')
@ns.param('todo_id', 'The task identifier')
class TodoSimple(Resource):

    @ns.marshal_with(todo_model)
    def get(self, todo_id):
        return store.get(todo_id)

    @ns.expect(todo_schema, validate=True)
    @ns.marshal_with(todo_model)
    def put(self, todo_id):
        return store.put(todo_id, api.payload)
```

In short, I'm using a `SchemaModel` in `expect()` and `Model` in `marshal_with`. 
(Note: I'm using PUT to do one-time-only creates with a fixed ID supplied from outside, so this doesn't quote match the demo materials.)

**Comment by JasonFinestone** [comment]
@KpaBap Thank you for your comment, I managed to get expect() working with a nested json request.

**Comment by 2Dews** [comment]
I am also receiving the AttributeError: 'SchemaModel' object has no attribute 'items' when trying to marshal with the following schema_model. 

I see the AttributeError is being thrown by the six.py package . The flask resplus package requires six 1.3 or above, I have six. 1.11 installed.  I tried rolling back to 1.3 but that broke a bunch of other stuff. 

My schema validates at jsonschemalint.com using version 4 and 6.

```python
sampleModel = api.schema_model('Sample', {
                                          'required': ['id', 'date', 'category'], 
                                          'properties': {
                                          'id':{'type': 'number'}, 
                                          'date':{'type': 'string', 'format': 'date-time'}, 
                                          'category':{'type': 'string'}
                                          },
                                          'type': 'object'
                                          })```

**Comment by latufla** [comment]
Generate JSON schema from marshmallow Shema. And use only @doc, not @marshall_with. This way you get swagger doc and marshmallow validation﻿

**Comment by shubhamgoyal42** [comment]
@DHager  - Thanks! using expect() worked for me too.

**Comment by hardikhhh1** [comment]
This works with expect, glad we reached there. But it should work with marshal_with, seems like a bug.

**Comment by varungbt** [comment]
I too have the same issue.  expect(json_schema) works fine, however marshall_with fails.

**Comment by flayman** [comment]
As a now deleted user mentioned [here](https://github.com/noirbizarre/flask-restplus/issues/438#issuecomment-460350182), you can simply use the @api.response decorator for marshalling. As far as I can see, it does the job equally well. It seems like the other decorators, i.e. marshal_with really ought to work though and the documentation suggests they would.

**Comment by alvarolopez** [comment]
We are hitting the same bug.

As @flayman says, using the `@api.response` decorator does the job to an extent (you cannot use an `envelop` with `@api.response`). However, I think that this is a valid but and that `@api.marshal_with` should work as well. The documentation suggest so, as it seems that using `schema_model` is just another way of defining models.
