### ISSUE TITLE
Error with CORS + 

### ISSUE THREAD

**Issue by brezniczky** [noirbizarre/flask-restplus#322]
We seem to be getting an "error: dict object is not callable" with relatively a simple code, once the result is a dictionary, not a string, from an API call decorated to allow for use for CORS.

We can live with that in the short run, but once a @api.marshal_with is put in place, things seem to fall over again (not investigated), which we'd like to utilize at some point.

Example (fawlty=False is a "fix"):

```
fawlty = True


@ns.route("/primitiveApi/")
class PrimitiveApi(Resource):

    @cross_origin(origin='*')
    def get(self):
        result = {"a": 5, "b": 6}
        if fawlty:
            return result
        else:
            return str(result)
```

Then the following is an example output:

```
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
--before_request--
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
Connection: keep-alive

Pragma: no-cache
Host: 127.0.0.1:5000
Upgrade-Insecure-Requests: 1
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate


--before_request end--
[2017-09-19 09:34:02,886] ERROR in app: Exception on /api/1/primitiveApi/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 309, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 191, in make_response
    return current_app.make_response(args)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 885, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 884, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
127.0.0.1 - - [19/Sep/2017 09:34:02] "GET /api/1/primitiveApi/ HTTP/1.1" 500 -
```

A full repro code is as below

```
from flask import Flask, Blueprint, request
from flask_restplus import Api, Resource
# from flask_cors import cross_origin
from flask_restplus import cors

api_v1 = Blueprint('api', __name__, url_prefix='/api/1')

api = Api(api_v1)

ns = api.namespace('')

fawlty = True


@ns.route("/primitiveApi/")
class PrimitiveApi(Resource):

    # @cross_origin(origin='*')
    @cors.crossdomain(origin='*')
    def get(self):
        result = {"a": 5, "b": 6}
        if fawlty:
            return result
        else:
            return str(result)


def init_app():
    app = Flask(__name__)

    app.register_blueprint(api_v1)
    return app


app = init_app()

@app.before_request
def before_request():
    print("--before_request--")
    print(request.headers)
    print("--before_request end--")


if __name__ == "__main__":
    app.run()
```

Maybe it's better reported on flask_cors?

Package list is as attached (sorry I didn't have time to narrow that aspect down/for virt.envs, maybe sometime later).

[POC_server_requirements.txt](https://github.com/noirbizarre/flask-restplus/files/1313573/POC_server_requirements.txt)

**Comment by brezniczky** [comment]
Note that the source mentioned in cors.py (http://flask.pocoo.org/snippets/56/) states "Snippets are unofficial and unmaintained." yet IMHO it's used all over the frameworks, so it could be useful to give the thing a review if it's confirmed as a bug.

**Comment by brezniczky** [comment]
Another framework that could benefit from an official fix is flask-restful.
