### ISSUE TITLE
expect argument in @api.doc breaks Swagger-UI

### ISSUE THREAD

**Issue by lec00q** [noirbizarre/flask-restplus#362]
The following example:

```
@api.doc(body=resource_fields)
def get():
    return
```

raises a `DeprecationWarning: The body attribute is deprecated, use expect instead`

However, modifying it to:

```
@api.doc(expect=resource_fields)
def get():
    return
```

remove the warning but breaks Swagger-UI:

```
webserver_1  | 2017-12-06 12:17:39 - app.py:1560 ERROR   - Exception on /api/v2/swagger.json [GET]
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
webserver_1  |     rv = self.dispatch_request()
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
webserver_1  |     return self.view_functions[rule.endpoint](**req.view_args)
webserver_1  |   File "/app/webserver/monkeypatches.py", line 29, in decorated_function
webserver_1  |     return func(*args, **kwargs)
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/api.py", line 313, in wrapper
webserver_1  |     resp = resource(*args, **kwargs)
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask/views.py", line 84, in view
webserver_1  |     return self.dispatch_request(*args, **kwargs)
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
webserver_1  |     resp = meth(*args, **kwargs)
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/api.py", line 771, in get
webserver_1  |     return self.api.__schema__
webserver_1  |   File "/usr/lib/python2.7/site-packages/werkzeug/utils.py", line 73, in __get__
webserver_1  |     value = self.func(obj)
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/api.py", line 472, in __schema__
webserver_1  |     self._schema = Swagger(self).as_dict()
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/swagger.py", line 168, in as_dict
webserver_1  |     paths[extract_path(url)] = self.serialize_resource(ns, resource, url, kwargs)
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/swagger.py", line 297, in serialize_resource
webserver_1  |     doc = self.extract_resource_doc(resource, url)
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/swagger.py", line 234, in extract_resource_doc
webserver_1  |     method_params = self.expected_params(method_doc)
webserver_1  |   File "/usr/lib/python2.7/site-packages/flask_restplus/swagger.py", line 246, in expected_params
webserver_1  |     for expect in doc.get('expect', []):
webserver_1  | TypeError: 'RequestParser' object is not iterable
```

**Comment by whatnick** [comment]
You have to pass a list to the *expect* keyword. Try *[resource_fields]* instead.
