### ISSUE TITLE
Is it possible to add custom, top-level attributes to swagger.json spec

### ISSUE THREAD

**Issue by woel0007** [noirbizarre/flask-restplus#441]
Now that 0.11.0 is released (+1 @noirbizarre ) I've incorporated the use of the `api.vendor()` decorator to add custom attributes to the paths/methods as needed.  However, is there a way to add a custom, top-level attribute to the swagger spec:

Something like:
```
swagger: '2.0'
basePath: /my_api/v2
x-api-definition: {"custom-attribute" : "custom-value"}
paths:
```

Is there a way to add this?

**Comment by TotempaaltJ** [comment]
Currently that isn't possible. You can work around this by overriding the Swagger class. Something like this should work (untested):

```
import logging

from flask_restplus import Api, Swagger
from werkzeug import cached_property

logger = logging.getLogger(__name__)


class CustomSwagger(Swagger):
    """Override RESTplus Swagger class to add custom properties."""

    def as_dict(self):
        """Add custom properties to top-level Swagger specs."""
        specs = super().as_dict()
        specs['x-api-definition'] = 'custom value'
        return specs


class CustomApi(Api):
    @cached_property
    def __schema__(self):
        """
        The Swagger specifications/schema for this API

        Override this to refer to our fixed Swagger class.

        :returns dict: the schema as a serializable dict
        """
        if not self._schema:
            try:
                self._schema = CustomSwagger(self).as_dict()
            except Exception:
                # Log the source exception for debugging purpose
                # and return an error message
                msg = 'Unable to render schema'
                logger.exception(msg)  # This will provide a full traceback
                return {'error': msg}
        return self._schema
```

After which you'll have to initiate RestPlus with your `CustomApi` class instead of the default `Api` (`api = CustomApi(app, ...)`).

**Comment by woel0007** [comment]
Thanks - this is helpful.  I really appreciate the suggestion.  

I tried this out - but I'm seeing an exception that I don't understand. (the exception comes when I start my app and try to generate the `swagger.json` file via a browser)   I don't fully grok how the swagger spec is being generated - any thoughts on what this one may mean?

```
[2018-05-23 14:29:06,149] ERROR in app: Exception on /bi_ra/v2/swagger.json [GET]
Traceback (most recent call last):
  File "/.envs/gs36/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/.envs/gs36/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/.envs/gs36/lib/python3.6/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/.envs/gs36/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/.envs/gs36/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/.envs/gs36/lib/python3.6/site-packages/flask_restplus/api.py", line 803, in get
    return schema, HTTPStatus.INTERNAL_SERVER_ERROR if 'error' in schema else HTTPStatus.OK
TypeError: argument of type 'method' is not iterable
127.0.0.1 - - [23/May/2018 14:29:06] "GET /bi_ra/v2/swagger.json HTTP/1.1" 500 -
```

**Comment by TotempaaltJ** [comment]
The only reason I can think of that this would happen is that the `@cached_property` decorator is somehow not working... That should prevent the `self.api.__schema__` call in line 802 of `api.py` from ever returning a method.

**Comment by woel0007** [comment]
Ah....  you're right - that was the issue.  Now that I've got `@cached_property` correctly in-place, this is working perfectly, thanks for all the help!
