### ISSUE TITLE
adding resource with 'resource_class_kwargs' is not working

### ISSUE THREAD

**Issue by BenjaminDev** [noirbizarre/flask-restplus#519]
Problem I'm trying to solve. Within a Resource I'd like to access a custom object. Perhaps I've missed something or there is a better way to do it. 

To reproduce:

`from flask import Blueprint
from flask_restplus import Api, Resource, fields

api_v1 = Blueprint('api', __name__, url_prefix='/api/1')

api = Api(api_v1, version='1.0', title='Todo API',
          description='A simple TODO API',
          )

ns = api.namespace('todos', description='TODO operations')

TODOS = {
    'todo1': {'task': 'build an API'},
    'todo2': {'task': '?????'},
    'todo3': {'task': 'profit!'},
}

todo = api.model('Todo', {
    'task': fields.String(required=True, description='The task details')
})

listed_todo = api.model('ListedTodo', {
    'id': fields.String(required=True, description='The todo ID'),
    'todo': fields.Nested(todo, description='The Todo')
})

def abort_if_todo_doesnt_exist(todo_id):
    if todo_id not in TODOS:
        api.abort(404, "Todo {} doesn't exist".format(todo_id))

parser = api.parser()
parser.add_argument('task', type=str, required=True, help='The task details', location='form')

#@ns.route('/<string:todo_id>')
@api.doc(responses={404: 'Todo not found'}, params={'todo_id': 'The Todo ID'})
class Todo(Resource):

    def __init__(self, **kwargs):
        self.test = kwargs['BotServerInputChannel']

    '''Show a single todo item and lets you delete them'''
    @api.doc(description='todo_id should be in {0}'.format(', '.join(TODOS.keys())))
    @api.marshal_with(todo)
    def get(self, todo_id):
        '''Fetch a given resource'''
        print(self.test*100)
        abort_if_todo_doesnt_exist(todo_id)

        return TODOS[todo_id]

    @api.doc(responses={204: 'Todo deleted'})
    def delete(self, todo_id):
        '''Delete a given resource'''
        abort_if_todo_doesnt_exist(todo_id)
        del TODOS[todo_id]
        return '', 204

    @api.doc(parser=parser)
    @api.marshal_with(todo)
    def put(self, todo_id):
        '''Update a given resource'''
        args = parser.parse_args()
        task = {'task': args['task']}
        TODOS[todo_id] = task
        return task

@ns.route('/')
class TodoList(Resource):
    '''Shows a list of all todos, and lets you POST to add new tasks'''
    @api.marshal_list_with(listed_todo)
    def get(self):
        '''List all todos'''
        return [{'id': id, 'todo': todo} for id, todo in TODOS.items()]

    @api.doc(parser=parser)
    @api.marshal_with(todo, code=201)
    def post(self):
        '''Create a todo'''
        args = parser.parse_args()
        todo_id = 'todo%d' % (len(TODOS) + 1)
        TODOS[todo_id] = {'task': args['task']}
        return TODOS[todo_id], 201
`

**Error:**
`[2018-08-31 18:45:39,392] ERROR in app: Exception on /api/1/todos/todo1 [GET]
Traceback (most recent call last):
  File "C:\Users\Benjamin\Documents\CortexLogic\CortexSolutions\ChatBots\ChatBotServer\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Benjamin\Documents\CortexLogic\CortexSolutions\ChatBots\ChatBotServer\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Benjamin\Documents\CortexLogic\CortexSolutions\ChatBots\ChatBotServer\venv\lib\site-packages\flask_restplus\api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\Benjamin\Documents\CortexLogic\CortexSolutions\ChatBots\ChatBotServer\venv\lib\site-packages\flask\views.py", line 87, in view
    self = view.view_class(*class_args, **class_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given`

**Version: ** 0.11.0
**Python** Python 3.6.4

**Comment by nickhalmagyi** [comment]
Hi, I think I have come across the same problem and have simplified the code. If I remove the 
```
def __init__(self):
    pass
```
then there is no erorr, but I want to keep the init so I can pass objects to the get-method.

```
from flask import Flask
from flask_restplus import Resource, Api

class HelloWorld(Resource):
    def __init__(self):
        pass
    def get(self):
        return {'hello': 'world'}

if __name__ == '__main__':
    app = Flask(__name__)
    api = Api(title='Hello World API')
    api.init_app(app)
    api.add_resource(HelloWorld, '/hello_world')
    app.run(debug=True)

```
Error:
```
Traceback (most recent call last):
  File "/Users/ganglion/Documents/Flask/flask_CR1/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ganglion/Documents/Flask/flask_CR1/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ganglion/Documents/Flask/flask_CR1/venv/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/ganglion/Documents/Flask/flask_CR1/venv/lib/python3.7/site-packages/flask/views.py", line 87, in view
    self = view.view_class(*class_args, **class_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given```

**Comment by YJinHai** [comment]
> 嗨，我想我遇到了同样的问题并简化了代码。如果我删除了
> 
> ```
> def __init__(self):
>     pass
> ```
> 然后没有erorr，但我想保留init，所以我可以将对象传递给get-method。
> 
> ```
> from flask import Flask
> from flask_restplus import Resource, Api
> 
> app = Flask(__name__)
> api = Api(title='Hello World API')
> 
> @api.route('/hello_world')
> class HelloWorld(Resource):
>     def __init__(self):
>         pass
>     def get(self):
>         return {'hello': 'world'}
> 
> if __name__ == '__main__':
>     api.init_app(app)
>     app.run(debug=True)
> ```
> 错误：
> 
> ```
> Traceback (most recent call last):
>   File "/Users/ganglion/Documents/Flask/flask_CR1/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/Users/ganglion/Documents/Flask/flask_CR1/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/Users/ganglion/Documents/Flask/flask_CR1/venv/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
>     resp = resource(*args, **kwargs)
>   File "/Users/ganglion/Documents/Flask/flask_CR1/venv/lib/python3.7/site-packages/flask/views.py", line 87, in view
>     self = view.view_class(*class_args, **class_kwargs)
> TypeError: __init__() takes 1 positional argument but 2 were given```
> ```
me too,Do you know why

**Comment by YJinHai** [comment]
I think this is the wrong design for this plus, right?

**Comment by YJinHai** [comment]
```python
@ns.route('/test', endpoint='dummy_path')
class DummyResource(Resource):

    def __init__(self, *args, **kwargs):
        self.reqparse = reqparse.RequestParser()
        self.reqparse.add_argument('arg_a', type=str, required=False,
                                   help='arg_a help')
        self.reqparse.add_argument('arg_b', type=str, required=False,
                                   help='arg_b help')
        super(DummyResource, self).__init__(*args, **kwargs)
```
This is the right way
