### ISSUE TITLE
Passing "doc=True" to the Api constructor gives a confusing result

### ISSUE THREAD

**Issue by alexwlchan** [noirbizarre/flask-restplus#534]
I was [reading the docs for disabling the Swagger UI endpoint](https://flask-restplus.readthedocs.io/en/stable/swagger.html#disabling-the-documentation):

> To disable Swagger UI entirely, set doc=False:
>
> ```python
> from flask import Flask
> from flask_restplus import Api
>
> app = Flask(__name__)
> api = Api(app, doc=False)
> ```

The natural opposite of `False` is `True`. Consider the following program:

```python
from flask import Flask, jsonify
from flask_restplus import Api

app = Flask(__name__)
api = Api(app, doc=True)
```

Running this code gives a horrible traceback; because it turns out the `doc` parameter is meant to be a string or a Falsey value, and `True` doesn't cut it!

```
Traceback (most recent call last):
  File "/Users/chana/.virtualenvs/tempenv-225030092748b/lib/python3.6/site-packages/flask_restplus/api.py", line 185, in init_app
    app.record(self._deferred_blueprint_init)
AttributeError: 'Flask' object has no attribute 'record'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner.py", line 8, in <module>
    doc=True
  File "/Users/chana/.virtualenvs/tempenv-225030092748b/lib/python3.6/site-packages/flask_restplus/api.py", line 152, in __init__
    self.init_app(app)
  File "/Users/chana/.virtualenvs/tempenv-225030092748b/lib/python3.6/site-packages/flask_restplus/api.py", line 188, in init_app
    self._init_app(app)
  File "/Users/chana/.virtualenvs/tempenv-225030092748b/lib/python3.6/site-packages/flask_restplus/api.py", line 199, in _init_app
    self._register_doc(self.blueprint or app)
  File "/Users/chana/.virtualenvs/tempenv-225030092748b/lib/python3.6/site-packages/flask_restplus/api.py", line 253, in _register_doc
    app_or_blueprint.add_url_rule(self._doc, 'doc', self.render_doc)
  File "/Users/chana/.virtualenvs/tempenv-225030092748b/lib/python3.6/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/chana/.virtualenvs/tempenv-225030092748b/lib/python3.6/site-packages/flask/app.py", line 1213, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
  File "/Users/chana/.virtualenvs/tempenv-225030092748b/lib/python3.6/site-packages/werkzeug/routing.py", line 602, in __init__
    if not string.startswith('/'):
AttributeError: 'bool' object has no attribute 'startswith'
```

I would suggest two things:

* Changing those docs to use `Api(app, doc=None)`, so there's less suggestion that `True` might work
* Improve the error message if you pass a truthy non-string value as the `doc` parameter

**Comment by vubon** [comment]
You are right. I was faced to same problem. In the constructor they used doc attribute as a string but in docs I saw a Boolean value.
So far I disabled the doc by using empty string . Such as doc=""

**Comment by FireByTrial** [comment]
I think the bigger issue here is that the documentation conflicts with what is actually expected in the code. I ended up doing something like this to deal with boolean values in my config file
```python
    app = Flask(__name__.split('.')[0])
    funky_params = {}
    if env.FLASK.get('SWAGGER_UI_ENABLED') is False:
        funky_params['doc'] = ''
    api = Api(
        authorizations=authorizations,
        security=['apiKey'],
        **funky_params
    )
    api.init_app(app)
    ...
```
I'll probably add some logic to handle changing the endpoint but that's not important for this issue
