### ISSUE TITLE
Missing 1 required positional argument

### ISSUE THREAD

**Issue by Nachtfeuer** [noirbizarre/flask-restplus#573]
The intended REST call was `http://localhost:5000/simple/hello2?message=iuujjopopj`.

## Error Code

```
[2019-01-23 10:13:36,531] ERROR in app: Exception on /simple/hello2 [GET]
Traceback (most recent call last):
  File "c:\Tools\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Tools\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Tools\Anaconda3\lib\site-packages\flask_restplus\api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "c:\Tools\Anaconda3\lib\site-packages\flask\views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "c:\Tools\Anaconda3\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: get() missing 1 required positional argument: 'message'
```

## Source Code

```python
from flask import Flask
from flask_restplus import Resource, Api

app = Flask(__name__)
api = Api(app, version='1.0')
ns = api.namespace('simple', description='Simple REST application')

@ns.route('/hello')
@ns.doc(description='Implements a simple hello world REST get request')
class HelloWorld(Resource):
    @ns.doc(description='Provide a simple JSON as response')
    def get(self):
        return {'hello': 'world'}


@ns.route('/hello2')
@ns.doc(description='Implements a simple hello world REST get request with a message')
@ns.param('message', 'a simple text message')
class HelloWorld(Resource):
    @ns.doc(description='Provide a simple JSON as response with the message')
    def get(self, message):
        return {'hello world': message}

if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by IsmoilovMuhriddin** [comment]
Changing some of the lines to parser has solved the getting parameter from url.

```python
from flask import Flask
from flask_restplus import Resource, Api
from flask_restplus import reqparse

parser = reqparse.RequestParser()
parser.add_argument('message', type=str, help='Message for printing')


app = Flask(__name__)
api = Api(app, version='1.0')
ns = api.namespace('simple', description='Simple REST application')

@ns.route('/hello')
@ns.doc(description='Implements a simple hello world REST get request')
class HelloWorld(Resource):
    @ns.doc(description='Provide a simple JSON as response')
    def get(self):
        return {'hello': 'world'}


@ns.route('/hello2')
@ns.doc(description='Implements a simple hello world REST get request with a message')
#@ns.param('message', 'a simple text message')
@ns.expect(parser)
class HelloWorld(Resource):
    @ns.doc(description='Provide a simple JSON as response with the message')
    def get(self, message=None):
    	args = parser.parse_args()
    	return {'hello world': args['message']}

if __name__ == '__main__':
    app.run(debug=True)```

But in source code of param decorator  (as far as I understood only for documentation purposes)
```python
    def param(self, name, description=None, _in='query', **kwargs):
        '''
        A decorator to specify one of the expected parameters

        :param str name: the parameter name
        :param str description: a small description
        :param str _in: the parameter location `(query|header|formData|body|cookie)`
        '''
        param = kwargs
        param['in'] = _in
        param['description'] = description
        return self.doc(params={name: param})
```

**Comment by aqellez** [comment]
@Nachtfeuer @ns.param used for params to api like id for requesting concrete object. It will be working if you will use route as
`@ns.route('/<int:id>')`
and make request to http://localhost:5000/simple/hello2/id , where id is integer number. Often it's id from db table.
But if you want to filter your request by some params you can use IsmoilovMuhriddin's solution or solution like this:

```python
import flask
....
class HelloWorld(Resource):
    @ns.doc(description='Provide a simple JSON as response with the message')
    def get(self):
        message = flask.request.args.get("message")
        return {'hello': message}

```
Now you try to go to http://localhost:5000/simple/hello2?message=world and use your params in get function.

**Comment by ziirish** [comment]
Hi,

Is this issue resolved?

**Comment by kasmediautamu** [comment]
uukjkjkjkjm
