### ISSUE TITLE
get_parent does not work as exptected

### ISSUE THREAD

**Issue by lvqier** [noirbizarre/flask-restplus#645]
1. When parent model is an empty dict:
```
>>> from flask_restplus import Namespace
>>> ns = Namespace('sample')
>>> ns.model('A', {})
>>> a = ns.model('A', {})
>>> b = ns.inherit('B', a, {})
>>> b.get_parent('A')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/sample/.tox/dev/lib/python3.5/site-packages/flask_restplus/model.py", line 67, in get_parent
    raise ValueError('Parent ' + name + ' not found')
ValueError: Parent A not found
>>> from flask_restplus import fields
>>> a = ns.model('A', {'a': fields.Integer()})
>>> b = ns.inherit('B', a, {})
>>> b.get_parent('A')
Model([('a', <flask_restplus.fields.Integer object at 0x7fe9c2ba1550>)])
```

2. When model has multiple parents
```
>>> from flask_restplus import fields
>>> a = ns.model('A', {'a': fields.Integer()})
>>> b = ns.inherit('B', a, {})
>>> b.get_parent('A')
Model([('a', <flask_restplus.fields.Integer object at 0x7fe9c2ba1550>)])
>>> c = ns.model('C', {'c': fields.Integer()})
>>> b = ns.inherit('B', c, a, {})
>>> b.get_parent('A')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/zjxta/.tox/dev/lib/python3.5/site-packages/flask_restplus/model.py", line 64, in get_parent
    found = parent.get_parent(name)
  File "/opt/zjxta/.tox/dev/lib/python3.5/site-packages/flask_restplus/model.py", line 67, in get_parent
    raise ValueError('Parent ' + name + ' not found')
ValueError: Parent A not found
```

**Comment by arabidopsis** [comment]
because the check in  `model.get_parent` is just `if found` but models
are instances of dictionaries... and a dictionary without elements is 'falsy'.
So A is not found because it is falsy. The get_parent method should really be something
like
```
    def get_parent(self, name):
        if self.name == name:
            return self
        else:
            for parent in self.__parents__:
                try:
                    return parent.get_parent(name)
               except ValueError:
                  pass
        raise ValueError("Parent " + name + " not found")
```
