### ISSUE TITLE
Using a list for "Multiple Locations" yields an unexpected exception

### ISSUE THREAD

**Issue by odi79** [noirbizarre/flask-restplus#725]
According to section "Multiple Locations" in the documentation (https://flask-restplus.readthedocs.io/en/stable/parsing.html) the following holds:

"Multiple argument locations can be specified by passing a list to location:
parser.add_argument('text', location=['headers', 'values'])
When multiple locations are specified, the arguments from all locations specified are combined into a single MultiDict. The last location listed takes precedence in the result set."

However, trying to use a list for the location parameter yields an exception when the "schema" method is executed.

### Example:

myargs = reqparse.RequestParser()
myargs.add_argument('label', type=str, required=True, help='Test', location=['values', 'json'])
...
@ns.expect(myargs)
...

### Expected behavior:

Due to the last location "json", the Swagger file should show 'in "body"' for that argument.

### Actual behavior:

Exception occuring since a list is unexpected.
```
2019-10-04 17:44:51,729 ERROR api: Unable to render schema
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/api.py", line 483, in __schema__
    self._schema = Swagger(self).as_dict()
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/swagger.py", line 177, in as_dict
    paths[extract_path(url)] = self.serialize_resource(ns, resource, url, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/swagger.py", line 336, in serialize_resource
    doc = self.extract_resource_doc(resource, url)
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/swagger.py", line 255, in extract_resource_doc
    method_params = self.expected_params(method_doc)
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/swagger.py", line 291, in expected_params
    parser_params = OrderedDict((p['name'], p) for p in expect.__schema__)
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/reqparse.py", line 405, in __schema__
    param = arg.__schema__
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/reqparse.py", line 269, in __schema__
    'in': LOCATIONS.get(self.location, 'query')
TypeError: unhashable type: 'list'
```
### Resolution:

**Current lines 265ff in reqparse.py:**
```
    @property 
    def __schema__(self):`
        if self.location == 'cookie':
            return
        param = {
            'name': self.name,
            'in': LOCATIONS.get(self.location, 'query')
        }
```
**New lines 265ff in reqparse.py:**
```
    @property
    def __schema__(self):
        if self.location == 'cookie':
            return
        if isinstance(self.location, six.string_types):
            location = self.location
        else:
            location = self.location[-1] # last location listed takes precedence in the result set, thus use this here
        param = {
            'name': self.name,
            'in': LOCATIONS.get(location, 'query')           
        }
```

**Comment by odi79** [comment]
And here's the diff for "reqparse.py" for the resoultion stated above:
```
265a266,269
>         if isinstance(self.location, six.string_types):
>             location = self.location
>         else:
>             location = self.location[-1]
268c272
<             'in': LOCATIONS.get(self.location, 'query')
---
>             'in': LOCATIONS.get(location, 'query')
```

**Comment by SteadBytes** [comment]
Well spotted! This looks fine to me, could you please create a PR for this including some more extensive for this in https://github.com/noirbizarre/flask-restplus/blob/816820a49076cb8a3f2461d5deabdde8ab8a8f30/tests/test_reqparse.py#L718 ?
