### ISSUE TITLE
Random appearing Type Error when encountering PUT or DELETE request with int data

### ISSUE THREAD

**Issue by liviubrinza** [noirbizarre/flask-restplus#757]
When doing PUT or DELETE requests with int data, I randomly (~ 6 times out of 10) get a type error stating that 'int' object is not iterable. The only similar issue I could find was submitted on the flask-restful git repository (https://github.com/flask-restful/flask-restful/issues/598) and it was closed in 2016, stating that it has been fixed in their 0.3.5 version. 
Being new to flask-restplus I am not sure whether I messed up something that I just cannot see.

This is the code for all the CRUD operations:

### **Code**

```python
from server import get_api
from flask_restplus import Resource, fields
from flask import request

from server.repositories.ComicsRepository import ComicsRepository

# server instance access
api = get_api()

# namespace setup
ns_comics = api.namespace('comics', description='Operations related to comics')

# Comic model definition
comic_model = api.model('Comic', {
		'name': fields.String(description='Comic name', required=True),
		'content': fields.String(description='Comic content', required=True)
                 })

# Comics repository instantiation
comics_repo = ComicsRepository(logger=api.app.logger)

@ns_comics.route("/")
@api.response(404, 'Comic not found')
class ComicCollection(Resource):
	def get(self):
		return comics_repo.get_all(), 200

	@api.expect(comic_model)
	def post(self):
		new_comic = request.json
		comic = comics_repo.add_comic(new_comic)
		return {'comic': comic}, 201

@ns_comics.route("/<int:resource_id>")
@api.response(404, 'Comic not found.')
@api.response(200, 'Success')
class CommicItem(Resource):
	def get(self, resource_id):
		comic = comics_repo.get_comic(resource_id)
		
		return comic, 200 if comic else None, 404

	@api.response(204, 'Comic successfully updated')
	@api.expect(comic_model)
	def put(self, resource_id):
		updated = comics_repo.update_comic(resource_id, request.json)

		return updated, 204 if updated else None, 404

	@api.response(204, 'Comic successfully deleted')
	def delete(self, resource_id):
		success = comics_repo.delete_comic(resource_id)

		return None, 204 if succes else None, 404
```

The error is thrown before the put method in the ComicItem class is reached. Tried doing PUT and DELETE calls from both the Swagger interface and Postman as well, with the same result. GET and POST requests work 100% of the time.

### **Stack Trace**

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 584, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 584, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 329, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 350, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/representations.py", line 28, in output_json
    resp.headers.extend(headers or {})
  File "/usr/local/lib/python3.6/site-packages/werkzeug/datastructures.py", line 1091, in extend
    for key, value in iterable:
TypeError: 'int' object is not iterable

### **Environment**
- Python version: 3.6
- Flask version: 1.1.1
- Flask-RESTPlus version: 0.13.0

![screen1](https://user-images.githubusercontent.com/33522926/70240303-a8deaf00-1775-11ea-8238-f90143b53c01.png)
![screen2](https://user-images.githubusercontent.com/33522926/70240312-ac723600-1775-11ea-815a-830a0960d911.png)

Any suggestion would be greatly appreciated.

**Comment by YellowFoxH4XOR** [comment]
can you please try the DELETE request and provide the stack trace.
also can you please add these 2 lines in the code.

The issue seems to be a value other than **int**

**import traceback**

@api.response(204, 'Comic successfully deleted')
	def delete(self, resource_id):
                **traceback.print_stack()**
		success = comics_repo.delete_comic(resource_id)

		return None, 204 if succes else None, 404

😄

**Comment by liviubrinza** [comment]
So, I've been trying for a couple of days to get the DELETE request to fail, but to no avail. Apparently that initial random behavior stabilized in the meantime. Now it seems like PUT never works, but DELETE is working fine ... I don't know why. I tried with both Python 3.8 and 3.6 because I was initially using 3.8 when the error first appeared. 
Anyway, I added the stack print in the PUT request, if that helps. The TypeError thrown remains the same as in my initial report.

   File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
     self._bootstrap_inner()
   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
     self.run()
   File "/usr/local/lib/python3.6/threading.py", line 864, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/local/lib/python3.6/socketserver.py", line 654, in process_request_thread
     self.finish_request(request, client_address)
   File "/usr/local/lib/python3.6/socketserver.py", line 364, in finish_request
     self.RequestHandlerClass(request, client_address, self)
   File "/usr/local/lib/python3.6/socketserver.py", line 724, in __init__
     self.handle()
   File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 327, in handle
     rv = BaseHTTPRequestHandler.handle(self)
   File "/usr/local/lib/python3.6/http/server.py", line 418, in handle
     self.handle_one_request()
   File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 362, in handle_one_request
     return self.run_wsgi()
   File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 304, in run_wsgi
     execute(self.server.app)
   File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 294, in execute
     for data in application_iter:
   File "/usr/local/lib/python3.6/site-packages/werkzeug/debug/__init__.py", line 330, in debug_application
     app_iter = self.app(environ, start_response)
   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
     return self.wsgi_app(environ, start_response)
   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
     resp = resource(*args, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 89, in view
     return self.dispatch_request(*args, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
     resp = meth(*args, **kwargs)
   File "/usr/src/app/server/controllers/ComicsController.py", line 55, in put
     traceback.print_stack()
 172.20.0.1 - - [09/Dec/2019 08:41:56] "PUT /comics/1 HTTP/1.1" 500 -

**Comment by YellowFoxH4XOR** [comment]
Can I get a link to your repository so I can debug the code?
