### ISSUE TITLE
flask_restx is not compatible with gunicorn

### ISSUE THREAD

**Issue by Serena-Xu** [noirbizarre/flask-restplus#799]
I am trying to use gunicorn to run the flask API that I just developed. It worked well when I use flask_restplus, but it had No module named 'flask_restx' when using flask_restx even I have flask_restx installed in my virtual environment. I think it might because gunicorn does not support flask_restx. Anyone had this issue before or has any idea about this?

### Below is my run.sh script

```
TIMEOUT=10000

echo "Starting gunicorn"
gunicorn \
    -b 0.0.0.0:80 \
    -t $TIMEOUT \
    -k gevent --worker-connections 10 \
    --keep-alive 3600 \
    --log-level info \
    bai.wsgi:app
```

When I try to run this script, it complains about ModuleNotFoundError: No module named 'flask_restx'.

Here is the trackback:

```
Starting gunicorn
[2020-07-19 11:43:11 -0400] [44134] [INFO] Starting gunicorn 19.9.0
[2020-07-19 11:43:11 -0400] [44134] [INFO] Listening at: http://0.0.0.0:80 (44134)
[2020-07-19 11:43:11 -0400] [44134] [INFO] Using worker: gevent
[2020-07-19 11:43:11 -0400] [44137] [INFO] Booting worker with pid: 44137
/Users/serenaxu/flask-template/BAI/bai/db/config.py:11: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  __baseconfig__ = yaml.load(open(CONFIG_PATH))
[2020-07-19 11:43:12 -0400] [44137] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/serenaxu/flask-template/BAI/bai/wsgi.py", line 2, in <module>
    from bai.app import create_app, create_api
  File "/Users/serenaxu/flask-template/BAI/bai/app.py", line 7, in <module>
    from bai import apis
  File "/Users/serenaxu/flask-template/BAI/bai/apis/__init__.py", line 2, in <module>
    from .namespace1 import main
  File "/Users/serenaxu/flask-template/BAI/bai/apis/namespace1.py", line 4, in <module>
    from flask_restx import Api, Resource, Namespace
ModuleNotFoundError: No module named 'flask_restx'
```

**Comment by karolpawlowski** [comment]
Are you sure you are in proper venv with flask_restx installed?
