### ISSUE TITLE
Nested models error

### ISSUE THREAD

**Issue by m-zajac** [noirbizarre/flask-restplus#8]
Models setup:

    api.model(name=u'User', model={
        'login': fields.String(
            description=u'Login',
            required=True,
        ),
        'public': fields.Nested({
            'email': fields.String(
                description=u'Email (if email public)',
                required=False,
            ),
            'nickname': fields.String(
                description=u'Nickname',
                required=False,
            ),
        }),
    })

    api.model(name=u'Register result', model={
        'errors': fields.List(
            fields.String,
            required=False,
            description=u'Error list',
        ),
        'user': fields.Nested(
            api.models['User'],
            description=u'created user object',
        ),
    })

Error on swagger ui request:

    Traceback (most recent call last):
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
        return original_handler(e)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restful/__init__.py", line 260, in error_router
        return self.handle_error(e)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
        return original_handler(e)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restful/__init__.py", line 260, in error_router
        return self.handle_error(e)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restful/__init__.py", line 431, in wrapper
        resp = resource(*args, **kwargs)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask/views.py", line 84, in view
        return self.dispatch_request(*args, **kwargs)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restful/__init__.py", line 521, in dispatch_request
        resp = meth(*args, **kwargs)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restplus/api.py", line 150, in get
        return Swagger(self.api).as_dict()
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restplus/swagger.py", line 248, in as_dict
        'definitions': self.serialize_definitions() or None,
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restplus/swagger.py", line 403, in serialize_definitions
        for name, model in self._registered_models.items()
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restplus/swagger.py", line 403, in <genexpr>
        for name, model in self._registered_models.items()
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restplus/swagger.py", line 388, in serialize_model
        prop = field_to_property(field)
      File "/home/maciek/.virtualenvs/pudelek-auth/lib/python2.7/site-packages/flask_restplus/swagger.py", line 116, in field_to_property
        prop = ref(nested_field.__apidoc__['name'])
    AttributeError: 'dict' object has no attribute '__apidoc__'

**Comment by wicol** [comment]
I would just like to say that I ran in to this issue just now (4 years later) because the documentation still states that it's possible to nest dicts: https://flask-restplus.readthedocs.io/en/latest/marshalling.html#nested-field

**Comment by painlessmartdatascience1** [comment]
For Me, This Worked : 
```
item_listing_order_model = api.model('ItemListingOrderSchema', {
    'user_id': fields.String(required=True),
    'items': fields.List(fields.Nested(api.model('ItemDetails',
        {
            'item_id': fields.Integer(
                description=u'Item ID',
                required=True,
            ),
            'listing_type_id': fields.Integer(
                description=u'Listing Type ID',
                required=True,
            ),
            'quantity': fields.Float(
                description=u'Nickname',
                required=True,
            ),
            'price': fields.Float(
                description=u'Nickname',
                required=True,
            ),
            'site_id': fields.Integer(
                description=u'Site ID',
                required=True,
            )

        }
    ))),
})
```

**Comment by vaibhavpatil123** [comment]
String contains valid json 
import com.fasterxml.jackson.databind.ObjectMapper;

public final class JSONUtils {
  private JSONUtils(){}

  public static boolean isJSONValid(String jsonInString ) {
    try {
       final ObjectMapper mapper = new ObjectMapper();
       mapper.readTree(jsonInString);
       return true;
    } catch (IOException e) {
       return false;
    }
  }
}

**Comment by vaibhavpatil123** [comment]
https://odieweblog.wordpress.com/2015/09/20/new-json-path-expression-predicates/https://odieweblog.wordpress.com/2015/09/20/new-json-path-expression-predicates/https://odieweblog.wordpress.com/2015/09/20/new-json-path-expression-predicates/https://odieweblog.wordpress.com/2015/09/20/new-json-path-expression-predicates/https://odieweblog.wordpress.com/2015/09/20/new-json-path-expression-predicates/

**Comment by j5awry** [comment]
@vaibhavpatil123 I'm more than a little confused about what you're posting on this old thread. 

1. You have a snippet of Java code related to Jackson
2. A link to an old blogpost about JSON and sql apparently?

Could you please provide info regarding what exactly you're looking for in regards to help in regards to flask-restplus? Also, if it's an issue not related to this closed ticket regarding nested models, please open a new ticket

**Comment by vaibhavpatil123** [comment]
https://github.com/dropwizard/dropwizard
